name: Badwars
version: '${version}'
main: bedwarsboys.badwars.Badwars
api-version: 1.18

commands:
  setarena:
    description: Sets the arena
    usage: /setarena <1|2> | <x> <y> <z> <1|2> | <x1> >y1> <z1> <x2> <y2> <z2>
    permission: badwars.setarena
  savearena:
    description: Saves the arena to the file with the name specified.
    usage: /savearena <name>
    permission: badwars.savearena