name: Badwars
version: '${version}'
main: bedwarsboys.badwars.Badwars
api-version: 1.18

commands:
  setarena:
    description: Sets the arena
    usage: /setarena <1|2> | <x> <y> <z> <1|2> | <x1> >y1> <z1> <x2> <y2> <z2>
    permission: badwars.setarena
  savearena:
    description: Saves the arena to the file with the name specified.
    usage: /savearena <name>
    permission: badwars.savearena
  pastearena:
    description: Loads and pastes the arena to the world
    usage: /pastearena <name>
    permission: badwars.pastearena
  summontestshop:
    description: summons a demo villager shop
    usage: /summontestshop
    permission: badwars.summontestshop
  configureteams:
    description: Lets you configure the number of teams and their colors
    usage: /configureteams
    permission: badwars.teams.config